# Generated by Django 4.2.18 on 2025-03-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Film', 'Film'), ('TV Show', 'TV Show')], max_length=10)),
                ('is_viewed', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
