# Generated by Django 4.2.19 on 2025-03-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_media_director_media_genre_media_plot_media_poster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='imdbID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
